version: '3.4'

services:

  gateway:
    image: "wechaty/wechaty:0.65"
    container_name: "wechatbot-gateway"
    restart: always
    environment:
      - WECHATY_LOG=${WECHATY_LOG}
      - WECHATY_PUPPET=${WECHATY_PUPPET}
      - WECHATY_PUPPET_PADLOCAL_TOKEN=${PADLOCAL_TOKEN}
      - WECHATY_PUPPET_SERVER_PORT=${WECHATY_PUPPET_SERVER_PORT}
      - WECHATY_TOKEN=${WECHATY_TOKEN}
    ports:
      - "${GATEWAY_SERVICE_PORT}:${WECHATY_PUPPET_SERVER_PORT}"
      
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
      network: host
    image: "bot:1.0"
    container_name: "wechatbot-bot"
    restart: always
    environment:
      - WECHATY_PUPPET_SERVICE_TOKEN=${PADLOCAL_TOKEN}
      - WECHATY_PUPPET_SERVICE_ENDPOINT=${GATEWAY_SERVICE_HOST}:${GATEWAY_SERVICE_PORT}
      - MESSAGE_SERVICE_ENDPOINT=${MESSAGE_SERVICE_HOST}:${MESSAGE_SERVICE_PORT}
    volumes:
      - "./bot:/bot"
    command: python3 /bot/bot.py
#    command: tail -f /dev/null
    depends_on:
      - gateway

  message:
    build:
      context: ./message
      dockerfile: Dockerfile
      network: host
    image: "message:1.0"
    container_name: "wechatbot-message"
    restart: always
    environment:
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_DB=${POSTGRES_DB}
      - PG_USER=${POSTGRES_USER}
      - PG_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${MESSAGE_SERVICE_PORT}:5000"
    volumes:
      - "./message:/message"
    command: python3 /message/app/start.py


  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
      network: host
    image: "dashboard:1.0"
    container_name: "wechatbot-dashboard"
    restart: always
    environment:
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_DB=${POSTGRES_DB}
      - PG_USER=${POSTGRES_USER}
      - PG_PASSWORD=${POSTGRES_PASSWORD}
      - MESSAGE_SERVICE_ENDPOINT=${MESSAGE_SERVICE_HOST}:${MESSAGE_SERVICE_PORT}
    ports:
      - "${DASHBOARD_SERVICE_PORT}:8050"
      - "122:22"
    volumes:
      - "./dashboard/app:/app"
    command: tail -f /dev/null
    depends_on:
      - postgres-db

  postgres-db:
    image: "postgres:11-bullseye"
    container_name: "wechatbot-postgres"
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TZ}
    ports:
      - "132:5432"
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
