version: '3.4'

services:

  gateway:
    image: "wechaty/wechaty:0.65"
    container_name: "wechatbot-gateway"
    restart: always
    env_file:
      - envfile/gateway.env
    ports:
      - "180:8080"
      
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
      network: host
    image: "bot:1.0"
    container_name: "wechatbot-bot"
    restart: always
    env_file:
      - envfile/bot.env
    volumes:
      - "/home/liangzhixing/WechatBot/bot:/bot"
    command: python3 /bot/bot.py
    depends_on:
      - gateway

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
      network: host
    image: "dashboard:1.0"
    container_name: "wechatbot-dashboard"
    restart: always
    env_file:
      - envfile/dashboard.env
    ports:
      - "150:8050"
      - "122:22"
    volumes:
      - "/home/liangzhixing/WechatBot/dashboard/app:/app"
    command: tail -f /dev/null

  postgres-db:
    image: "postgres:11-bullseye"
    container_name: "wechatbot-postgres"
    restart: always
    env_file:
      - envfile/postgres.env
    ports:
      - "132:5432"
    volumes:
      - "/home/liangzhixing/WechatBot/postgres/data:/var/lib/postgresql/data"
