version: '3.4'

services:

  gateway:
    image: "wechaty/wechaty:0.65"
    container_name: "wechatbot-gateway"
    restart: always
    env_file:
      - envfile/gateway.env
    ports:
      - "5678:8080"
      
  wechatbot:
    build:
      context: ./wechatbot
      dockerfile: Dockerfile
      network: host
    image: "wechatbot:1.0"
    container_name: "wechatbot-wechatbot"
    restart: always
    env_file:
      - envfile/wechatbot.env
    ports:
      - "5022:22"
    command: tail -f /dev/null

  pg:
    image: "postgres:11-bullseye"
    restart: always
    env_file:
      - envfile/pg.env
    container_name: wechatbot-pg
    ports:
      - "5432:5432"
#    volumes:
#      - ./data:/var/lib/postgresql/data
